export const QUERY_KEYS = {
  challenges: 'challenges',
  CHALLENGES: 'challenges',
  challenge: (id: number | string) => ['challenges', id],
  CHALLENGE: (id: number | string) => ['challenges', id],
  scoreboard: 'scoreboard',
  SCOREBOARD: 'scoreboard',
  scoreboardTop: (count: number) => ['scoreboard', 'top', count],
  SOLVES: (id: number | string) => ['solves', id],
  users: 'users',
  teams: 'teams',
  hints: 'hints',
  notifications: 'notifications',
  pages: 'pages',
  configs: 'configs',
  brackets: 'brackets',
  flags: (challengeId: number) => ['flags', challengeId],
  flagTypes: 'flag-types',
  challengeTypes: 'challenge-types',
  adminChallenges: 'admin-challenges',
  adminChallenge: (id: number) => ['admin-challenges', id],
  adminUsers: 'admin-users',
  adminUser: (id: number) => ['admin-users', id],
  adminTeams: 'admin-teams',
  adminTeam: (id: number) => ['admin-teams', id],
  adminSubmissions: 'admin-submissions',
  adminPages: 'admin-pages',
  adminNotifications: 'admin-notifications',
}

export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  confirm: '/confirm',
  resetPassword: '/reset-password',
  challenges: '/challenges',
  scoreboard: '/scoreboard',
  notifications: '/notifications',
  users: '/users',
  user: (id: number | string) => `/users/${id}`,
  teams: '/teams',
  team: (id: number | string) => `/teams/${id}`,
  settings: '/settings',
  setup: '/setup',
  admin: {
    index: '/admin',
    challenges: '/admin/challenges',
    challenge: (id: number | string) => `/admin/challenges/${id}`,
    users: '/admin/users',
    user: (id: number | string) => `/admin/users/${id}`,
    teams: '/admin/teams',
    team: (id: number | string) => `/admin/teams/${id}`,
    submissions: '/admin/submissions',
    pages: '/admin/pages',
    notifications: '/admin/notifications',
    config: '/admin/config',
    statistics: '/admin/statistics',
    reset: '/admin/reset',
    plugin: '/admin/plugin',
  },
}

export const API_BASE = '/api/v1'
